### ISSUE TITLE
Add zone: Can't click Save

### ISSUE THREAD

**Issue by mkaboldy** [ArPIHomeSecurity/arpi_webapplication#4]
https://demo.arpi-security.info/zone/add

can't click Save button even though all mandatory fields are filled

**Comment by gkovacs81** [comment]
Thanks for the first issue! :)

TLDR: check if there is a running alert or movement on the sensors. You can make configuration changes when the system is in ready state (sensors are green).

---
There are some restrictions when it's not allowed to do configuration changes (and maybe also some bugs). Unfortunatelly the easiest solution was to disable the action buttons in such cases, but I know a message box with a good hint would help a lot. Adding more help to the application is also on my roadmap, but only if others think the project usefull.

**Comment by mkaboldy** [comment]
The project IS useful!

a simple conditional alert would do the job:)

`<div class="alert alert-warning" @ngIf="!MonitoringState.READY">Config change is not allowed until the system is in ready state</div>`

(bootstrap style example)

**Comment by gkovacs81** [comment]
I found a bug in the validation of the form. Thanks for reporting it!
I'm working on the hint message!
